spring.application.name=backend

# The connection string to Docker container
spring.datasource.url=jdbc:postgresql://localhost:5432/transit_db
spring.datasource.username=postgres
spring.datasource.password=password

# Tell Hibernate not to auto-generate tables, Flyway is in charge of creating tables
spring.jpa.hibernate.ddl-auto=validate

# turn on Flyway
spring.flyway.enabled=true
